---
title: "Exercise 1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.

	
## Exercise 1

1. Google Studies - Adding 8" plates along with 12" plates in Google's cafeteria.

After running an experiment, Google found that stocking cafeterias with 8-inch plates alongside 12-inch plates encouraged people to eat smaller, healthier portions.
 
Following is the most likely design of the study using experimental design notation:
	
	NR	O1	X	 O2
	
NR = Non-random assignment as the study seems to have been done for all employees irrespective of their food choices or taste	

O1 = Employees ate larger and less healthier portions of food using 12-inch plates 

X = Introduction of 8-inch plates along with 12-inch plates in the cafeteria	

O2 = Employees encouraged to eat smaller and healthier portions of food thereby improving employee health by reduction of the calorie intake of the employees


	
This experiment used a within-subjects design to test treatment without a control group. In these designs, you usually compare one group’s outcomes before and after a treatment (instead of comparing outcomes between different groups). 


Potential threats to inference and ways to address:
	

•	For strong internal validity, it’s usually best to include a control group if possible. In this case, the experiment was only conducted on a treatment group in a non-random manner. In the absence of a control group, there was no way to determine if the improvement in their employee health was a result of the introduction of 8-inch plates thus enforcing choice of smaller and healthier food portions on the employees. There could have been many other potential factors contributing to this overall employee health improvement. A better way to infer this would have been to introduce a control group who would have only been given the option of 12-inch plates and then study if the portions of food intake was still smaller and healthier amongst the employees. If yes, then most probably there were other factors contributing to this phenomenon such as awareness and lifestyle changes, etc. A comparison between the two groups would have given a clearer idea.


•	As touched upon in previous point, there could have been other potential factors contributing to employee health improvement apart from just encouragement from introduction of 8-inch plates. The best way to figure out would be to conduct a survey amongst the employees to see how many of them are into specific diets and exercise regime. Those employees would have nonetheless opted for smaller and healthier portions of food regardless of plate size. 

•	While picking a random group is always best to deduce conclusions but, in this case, it would have been better to isolate the employee group that does not fall into the category of one with special diet/exercise regime as described in point 2 above. Conducting the experiment on this group (non-random) with split between treatment and control sub-groups would have derived accurate results.


Challenges:

Very limited backdrop and data regarding the scenario.
Need further info on how many employees actually avail the cafeteria services and how was the employee health assessed. How much was the correlation between the two? 
Info regarding the menu, if at all any changes (more healthier options) were introduced during the course of the experiment.





	

2. Managerial Practices Challenge

Manager’s motivation tactics → Employee Perf. 
Motivation Tactic A                       9% I        91% D 
Motivation Tactic B                       91% I        9% D 

“Expert” says Tactic A HELPS employee performance and Tactic B HARMS employee performance. How to figure out who is right?


From the performance data analysis of 1000 employees, tactic A and tactic B both have similar average employee performance. However, the Coefficient of variation for tactic A is slightly higher than that for tactic B, thus making tactic A causing the decrease in employee performance.  Cumulative change in employee performance, No.of people benefitted as well as incremental and decremental change for both A and B compared also show tactic B performing better than tactic A. (See excel sheet)
Hence from the analysis of the given data, tactic B seems to be better performing than tactic A. However, the given statistic of 9% - 91% is something that I cannot directly correlate to the given data.

As per the expert, however, tactic A is better than tactic B. This could be due to various factors. We have no idea of the data analysed by the expert to deduce the conclusion. Maybe the data analysed was different than the given one and at a later time when more statistics evolved wrt both the tactics on employee performance. In addition,
it appears that both tactics are employed on the same individual. It is most likely they were applied one after the other. Therefore, the effect of the second tactic on employee performance is cognizant of the first tactic and may or may not have a compounding effect. There is a slight chance in this manner tactic A could have helped with employee performance in comparison to tactic B. Lastly the measure of success of employee performance could always differ with different analysis as pointed out by most of the fellow classmates. So there is no way we can simply say if the expert is right or wrong in his analysis but yes based on the given data it does not correlate.
	
	
	
	
	

